[manager]
52.2.225.52 ansible_user=ubuntu ansible_ssh_private_key_file=~/DevOps_Assignment/terraform/terraform-key.pem ansible_python_interpreter=/usr/bin/python3

[workers]
98.85.239.118 ansible_user=ubuntu ansible_ssh_private_key_file=~/DevOps_Assignment/terraform/terraform-key.pem ansible_python_interpreter=/usr/bin/python3
52.23.8.163 ansible_user=ubuntu ansible_ssh_private_key_file=~/DevOps_Assignment/terraform/terraform-key.pem ansible_python_interpreter=/usr/bin/python3
